--Installs all canilsen ccscripts
shell.run("clear")
shell.run("pastebin get KLwkGt1h startup")
shell.run("clear")
print("Installed 1/6")
shell.run("pastebin get 8FtKixZF miner")
shell.run("clear")
print("Installed 2/6")
shell.run("pastebin get 4U51FsbV torch")
shell.run("clear")
print("Installed 3/6")
shell.run("pastebin get 948f2xBB clearline")
shell.run("clear")
print("Installed 4/6")
shell.run("pastebin get nwbMXdvr line")
shell.run("clear")
print("Installed 5/6")
shell.run("pastebin get qQzpmXNZ pillar")
shell.run("clear")
print("Installed 6/6: startup, miner, torch, clearline, line, pillar.")